/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "APP/main.h"


int main(void)
{
	//System clock Enable
    RCC_vInitSystemCLK();
    //Peripherals clock enable
    RCC_vEnableClock(AHB1_BUS, PERIPHERAL_EN_GPIOA);
    RCC_vEnableClock(AHB1_BUS, PERIPHERAL_EN_GPIOB);
    RCC_vEnableClock(AHB1_BUS, PERIPHERAL_EN_GPIOD);
    RCC_vEnableClock(AHB1_BUS, PERIPHERAL_EN_GPIOE);
    RCC_vEnableClock(AHB1_BUS, PERIPHERAL_EN_GPIOH);
    RCC_vEnableClock(APB2_BUS, PERIPHERAL_EN_ADC1);
    // Initializations
    STK_Init(STK_CLK_SRC_HCLK);
    MADC_VoidADCInit(_1_Conversion);
    MADC_VoidADCEnable();

    HLDR_vInit();
    H_TempSensor_Void_TempSensorInit();
    LCD_enuInit();



    //RCC_vEnableClock(APB2_BUS, PERIPHERAL_EN_ADC1);
    GPIO_vSetMode(GPIO_E, Pin0, GPIO_Output);
    GPIO_vSetPullUpPullDown(GPIO_E, Pin0, Float);
    GPIO_vSetType(GPIO_E, Pin0, PushPull);
    GPIO_vSetSpeed(GPIO_E, Pin0, LowSpeed);


    GPIO_vSetMode(GPIO_E, Pin15, GPIO_Input);
    GPIO_vSetPullUpPullDown(GPIO_E, Pin15, Pull_Down);
    GPIO_vSetType(GPIO_E, Pin15, PushPull);
    GPIO_vSetSpeed(GPIO_E, Pin15, LowSpeed);

    GPIO_vSetMode(GPIO_D, Pin0, GPIO_Output);
    GPIO_vSetPullUpPullDown(GPIO_D, Pin0, Float);
    GPIO_vSetType(GPIO_D, Pin0, PushPull);
    GPIO_vSetSpeed(GPIO_D, Pin0, LowSpeed);

	//LCD PINs
	for(int i =0; i<16; i++)
	{
		GPIO_vSetMode(GPIO_D, i, GPIO_Output);
		GPIO_vSetPullUpPullDown(GPIO_D, i, Float);
		GPIO_vSetType(GPIO_D, i, PushPull);
		GPIO_vSetSpeed(GPIO_D, i, LowSpeed);
	}

   // GPIO_vGetPinValue(GPIO_H, Pin1, &a);
    IR_vSENSOR_ENABLE();
    IR_vSENSOR_DATA_PIN_MODE();
    u8 L_u8Flag =0 ;
    while(1)
    	{
    		//Task1 LDR(AH) : At day lights on with medium intensity at night lights off
    		if( HLDR_u8LdrRead() == 1)
    		{
    			GPIO_vWritePinValue(GPIO_D, Pin0, HighState);
    			//GPIO_vWritePinValue(GPIO_E, Pin0, HighState);
    			L_u8Flag = 1;
    		}
    		else
    		{
    			GPIO_vWritePinValue(GPIO_D, Pin0, LowState);
    			//GPIO_vWritePinValue(GPIO_E, Pin0, LowState);
    			L_u8Flag =0;
    		}
    		//Task2 IR Sensor(MS) : if there is a car lights on with max intensity
    		if(L_u8Flag == 1)
    		{
    			if (IR_vSENSOR_READ() == 1)
    			{
    				GPIO_vWritePinValue(GPIO_E, Pin0, HighState);
    			}
    			else
    			{
   	    			GPIO_vWritePinValue(GPIO_E, Pin0, LowState);
    			}
    		}


    		// task3 TEMP Sensor : Detect Fire

    		u16 L_TempRead = H_TempSensor_U16_TempSensorRead();
        	if ( L_TempRead >= 50)
            {
    			LCD_enuGoToPosition(1, 1);
    			LCD_enuWriteString("TEMP > 50");
        		GPIO_vWritePinValue(GPIO_D, Pin8, HighState);
        		Delay_vMsIn16MHz(50);
        		GPIO_vWritePinValue(GPIO_D, Pin8, LowState);
        		Delay_vMsIn16MHz(50);
        		GPIO_vWritePinValue(GPIO_D, Pin8, HighState);
    			LCD_enuGoToPosition(2, 1);
    			LCD_enuWriteString("<-----FIRE----->");
            }
        	else
        	{
    			LCD_enuGoToPosition(1, 1);
    			LCD_enuWriteString("TEMP < 50");
        		GPIO_vWritePinValue(GPIO_D, Pin8, LowState);
    			LCD_enuGoToPosition(2, 1);
    			LCD_enuWriteString("<-----SAFE----->");
        	}
    	}

}

