/*
 * SPI_Config.h
 *
 *  Created on: Jun 27, 2022
 *      Author: musta
 */

#ifndef MCAL_SPI_SPI_CONFIG_H_
#define MCAL_SPI_SPI_CONFIG_H_


/*
 * Choose SPI data order :
 *
 * SPI_DATA_ORDER_MSB_FIRST
 * SPI_DATA_ORDER_LSB_FIRST
 */

#define SPI_DATA_ORDER			SPI_DATA_ORDER_LSB_FIRST

/*
 * Choose SPI clk polarity :
 *
 * SPI_CLK_POLARITY_IDLE_LOW
 * SPI_CLK_POLARITY_IDLE_HIGH
 */

#define SPI_CLK_POLARITY		SPI_CLK_POLARITY_IDLE_HIGH

/*
 * Choose SPI clk phase :
 *
 * SPI_CLK_PHASE_SAMPLE_FIRST
 * SPI_CLK_PHASE_SAMPLE_LAST
 */

#define SPI_CLK_PHASE			SPI_CLK_PHASE_SAMPLE_LAST

/*
 * Choose SPI clk speed mode :
 *
 * SPIT_CLK_SPEED_MODE_NORMAL
 * SPIT_CLK_SPEED_MODE_DOUBLE
 */


#define SPI_CLK_SPEED_MODE		SPIT_CLK_SPEED_MODE_NORMAL

/*
 * Choose SPI clk speed :
 *
 * SPIT_CLK_SPEED_MODE_NORMAL:
 *
 * SPI_CLK_RATE_NORMAL_MODE_4
 * SPI_CLK_RATE_NORMAL_MODE_16
 * SPI_CLK_RATE_NORMAL_MODE_64
 * SPI_CLK_RATE_NORMAL_MODE_128
 *
 *
 * SPIT_CLK_SPEED_MODE_DOUBLE:
 *
 * *SPI_CLK_RATE_DOUBLE_MODE_2
 * SPI_CLK_RATE_DOUBLE_MODE_8
 * SPI_CLK_RATE_DOUBLE_MODE_32
 * SPI_CLK_RATE_DOUBLE_MODE_64
 */

#define SPI_CLK_RATE			SPI_CLK_RATE_NORMAL_MODE_4

#endif /* MCAL_SPI_SPI_CONFIG_H_ */
